apiVersion: apps/v1
kind: Deployment
metadata:
  name: ham-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ham-deploy
  template:
    metadata:
      labels:
        name: ham-deploy
    spec:
      serviceAccountName: ham-deploy
      containers:
        - name: ham-deploy
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - ham-deploy
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ham-deploy"
