apiVersion: apps/v1
kind: Deployment
metadata:
  name: ham-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ham-deploy
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        name: ham-deploy
    spec:
      serviceAccountName: ham-deploy
      containers:
        - name: ham-deploy
          # Replace this with the built image name
          image: quay.io/hybridappio/ham-deploy:latest
          command:
          - ham-deploy
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ham-deploy"
