kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ham-deploy
subjects:
- kind: ServiceAccount
  namespace: default
  name: ham-deploy
roleRef:
  kind: ClusterRole
  name: ham-deploy
  apiGroup: rbac.authorization.k8s.io
