apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ham-deploy
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  - deployments/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ham-deploy
rules:
- apiGroups:
  - mcm.ibm.com
  resources:
  - clusterstatuses/log
  verbs:
  - get
- apiGroups:
  - deploy.hybridapp.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - core.hybridapp.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - tools.hybridapp.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - pods
  - serviceaccounts
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - app.ibm.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - managedclusters/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - proxy.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - view.open-cluster-management.io
  resources:
  - managedclusterviews
  verbs:
  - '*'
- apiGroups:
  - clusterregistry.k8s.io
  resources:
  - clusters
  - clusters/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - app.k8s.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - applicationassemblers.core.hybridapp.io
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - channels.apps.open-cluster-management.io
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - deployables.core.hybridapp.io
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - deployers.core.hybridapp.io
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - deployersets.core.hybridapp.io
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - placementrules.apps.open-cluster-management.io
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - subscriptions.apps.open-cluster-management.io
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - deployables.apps.open-cluster-management.io
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: hybrid-application-model
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'