apiVersion: deploy.hybridapp.io/v1alpha1
kind: Operator
metadata:
  name: simple
spec:
  license:
    accept: true
  core:
    deployable:
      enabled: true
  tools:
    assembler:
      enabled: true
    discoverer:
      enabled: false


